In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
n = 4

In [ ]:
grid = np.zeros([n+2, n+2], dtype=int)
grid

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
    #.       top.       down.      left.         right
input_argv = "4 2 1 2 " + "1 2 4 2 " + "3 2 2 1 " + "2 3 1 2"
input_argv

'4 2 1 2 1 2 4 2 3 2 2 1 2 3 1 2'

In [ ]:
input_argv.split()
input_int = np.array([int(x) for x in input_argv.split()])
input_int

array([4, 2, 1, 2, 1, 2, 4, 2, 3, 2, 2, 1, 2, 3, 1, 2])

In [ ]:
input_int.shape

(16,)

In [ ]:
matrix_input = input_int.reshape([4,4])
matrix_input

array([[4, 2, 1, 2],
       [1, 2, 4, 2],
       [3, 2, 2, 1],
       [2, 3, 1, 2]])

In [ ]:
matrix_input[0]

array([4, 2, 1, 2])

In [ ]:
matrix_input[0][0]

4

In [ ]:
grid

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
grid_fill = grid.copy()
grid_fill[0]

array([0, 0, 0, 0, 0, 0])

In [ ]:

grid

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
grid_fill[0][1:-1] = matrix_input[0]


In [ ]:
grid_fill[3+2][1:-1] = matrix_input[1]
grid_fill


array([[0, 4, 2, 1, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 2, 4, 2, 0]])

In [ ]:
grid_fill

array([[0, 4, 2, 1, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 2, 4, 2, 0]])

In [ ]:
matrix_input[2]
# grid_fill[3+2][1:-1] = matrix_input[1]

array([3, 2, 2, 1])

In [ ]:
grid_fill[1:-1, 0] = matrix_input[2]
grid_fill

array([[0, 4, 2, 1, 2, 0],
       [3, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 2, 4, 2, 0]])

In [ ]:
grid_fill[1:-1, 5] = matrix_input[3]
grid_fill

array([[0, 4, 2, 1, 2, 0],
       [3, 0, 0, 0, 0, 2],
       [2, 0, 0, 0, 0, 3],
       [2, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 2],
       [0, 1, 2, 4, 2, 0]])

In [ ]:
gf = grid_fill.copy()
      #check_case(row, col)
n = 4
#for row in range(n+2):
for row in range(0):
  for col in range(n+2):
    if (row == 0 or row == 5 or col == 0 or col == 5):
      print(f"\"{row}, {col}\"", end=" ")
      #print("[#, #]", end=" ")
      continue
    else:
      if (gf[row, col] == 1):
        gf[row + 1, col] = 4
      print([row,col], end=" ")
  print("\n")

In [ ]:
gf

array([[0, 4, 2, 1, 2, 0],
       [3, 0, 0, 0, 0, 2],
       [2, 0, 0, 0, 0, 3],
       [2, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 2],
       [0, 1, 2, 4, 2, 0]])

In [ ]:
from itertools import permutations, product, combinations

In [ ]:
for i, val in enumerate(permutations([1,2,3,4])):
  print(i + 1, val)
# f
# 2: t
# 3 :t
# 4 : t
# 5 : f
# 6 : f
# 7 : t
# 8 : f
# 9 : t
# 10: t
# 11: f
# 12: f
# 13: f
# 14: f
# 15: f
# 16: f
# 17: f
# 18: f
# 19: f
# .... 24: f


1 (1, 2, 3, 4)
2 (1, 2, 4, 3)
3 (1, 3, 2, 4)
4 (1, 3, 4, 2)
5 (1, 4, 2, 3)
6 (1, 4, 3, 2)
7 (2, 1, 3, 4)
8 (2, 1, 4, 3)
9 (2, 3, 1, 4)
10 (2, 3, 4, 1)
11 (2, 4, 1, 3)
12 (2, 4, 3, 1)
13 (3, 1, 2, 4)
14 (3, 1, 4, 2)
15 (3, 2, 1, 4)
16 (3, 2, 4, 1)
17 (3, 4, 1, 2)
18 (3, 4, 2, 1)
19 (4, 1, 2, 3)
20 (4, 1, 3, 2)
21 (4, 2, 1, 3)
22 (4, 2, 3, 1)
23 (4, 3, 1, 2)
24 (4, 3, 2, 1)


In [ ]:
tower_heights = [-1, 1, 2, 3, 4]
aph = list(permutations(tower_heights))
aph = np.array(aph)
aph.shape

(120, 5)

In [ ]:
list(combinations([1, 2, 3], 2))

[(1, 2), (1, 3), (2, 3)]

In [ ]:
aph[:5].tolist()[0]

[-1, 1, 2, 3, 4]

In [ ]:
list(combinations(aph[:5].tolist()[0], 4))

[(-1, 1, 2, 3), (-1, 1, 2, 4), (-1, 1, 3, 4), (-1, 2, 3, 4), (1, 2, 3, 4)]

In [ ]:
aph[:3]

array([[-1,  1,  2,  3,  4],
       [-1,  1,  2,  4,  3],
       [-1,  1,  3,  2,  4]])

In [ ]:
view_heights = [1, 2, 3, 4]
vh = np.array(list(product(view_heights, repeat=2)))
vh.shape

(16, 2)

In [ ]:
# 1. base case : fixed case : manual case 
# 2. while (all grid is not filled):
        # check_and_fill()

        # if all grid is filled 
            # break;

In [ ]:
# 1. base case : fixed case : manual case 
# 2. check_and_fill() {
    #      check_and_fill()
    #.     if (fill_all_grid)
#.          return;
#}


In [ ]:
# def check(v1, v2, arr):


In [ ]:
# aph
# vh

In [ ]:
5*4*3*2

120

In [ ]:
  16 * 120

1920

In [ ]:
16 * 120 * 5

9600

In [ ]:
all_available_logic = []
# person left, r
def is_logic_good(p_l, arr, p_r):
#def is_logic_good(1, [-1, 1, 2, 4], 2):
#def is_logic_good(1, [-1, -1, -1, -1], 2):
#  int max;
#  for tower_h in arr:
  if (p_l == 1 and p_r ==1):
    arr = 

  ...
#  1 (-1, 1, 2, 4) 2

  #if (p_l)

length = 0
for vh_i in vh[:2]:
  for a_i, aph_i in enumerate(aph[:2]):
    print(vh_i[0], aph_i, vh_i[1])
    print("aph_{}\n--------------".format(a_i))
    print("comb")
    for comb in combinations(aph_i, 4):
      print(vh_i[0], comb, vh_i[1])
      is_logic_good()
    # print(aph_i) 
    length += 1


1 [-1  1  2  3  4] 1
aph_0
--------------
comb
1 (-1, 1, 2, 3) 1
1 (-1, 1, 2, 4) 1
1 (-1, 1, 3, 4) 1
1 (-1, 2, 3, 4) 1
1 (1, 2, 3, 4) 1
1 [-1  1  2  4  3] 1
aph_1
--------------
comb
1 (-1, 1, 2, 4) 1
1 (-1, 1, 2, 3) 1
1 (-1, 1, 4, 3) 1
1 (-1, 2, 4, 3) 1
1 (1, 2, 4, 3) 1
1 [-1  1  2  3  4] 2
aph_0
--------------
comb
1 (-1, 1, 2, 3) 2
1 (-1, 1, 2, 4) 2
1 (-1, 1, 3, 4) 2
1 (-1, 2, 3, 4) 2
1 (1, 2, 3, 4) 2
1 [-1  1  2  4  3] 2
aph_1
--------------
comb
1 (-1, 1, 2, 4) 2
1 (-1, 1, 2, 3) 2
1 (-1, 1, 4, 3) 2
1 (-1, 2, 4, 3) 2
1 (1, 2, 4, 3) 2
